### ISSUE TITLE
Installer fails on Fedora 29

### ISSUE THREAD

**Issue by kodegeek-test** [qeeqbox/social-analyzer#3]
```
[xxx@mac-pro-1-1 social-analyzer]$ sudo  dnf install -y tesseract
```
```
[xxx@mac-pro-1-1 social-analyzer]$ npm install
npm WARN social-analyzer@1.0.0 No repository field.
npm WARN social-analyzer@1.0.0 license should be a valid SPDX license expression

audited 170 packages in 1.74s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[xxx@mac-pro-1-1 social-analyzer]$ npm start

> social-analyzer@1.0.0 start /home/josevnz/social-analyzer
> node server.js

internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/home/josevnz/social-analyzer/node_modules/klona'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/josevnz/social-analyzer/node_modules/sanitize-html/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! social-analyzer@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the social-analyzer@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/josevnz/.npm/_logs/2020-12-24T19_05_42_315Z-debug.log
```

**Comment by giga-a** [comment]
Hey,

Try deleting package-lock.json and npm install inside social analyzer folder

rm -rf package-lock.json node_modules
npm install
npm start

**Comment by kodegeek-test** [comment]
Hello,

It makes no difference. Same error:
```
[xxx@mac-pro-1-1 social-analyzer]$ npm start

> social-analyzer@1.0.0 start /home/xxx/social-analyzer
> node server.js

internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/home/xxx/social-analyzer/node_modules/klona'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/josevnz/social-analyzer/node_modules/sanitize-html/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! social-analyzer@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the social-analyzer@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2020-12-26T12_45_33_489Z-debug.log
```
Thanks for looking into this. It is a bummer that I cannot pass from the installation stage.

**Comment by giga-a** [comment]
Alright, would you be able to tell what node and npm versions do you have?

node -v
npm -v

**Comment by kodegeek-test** [comment]
Sure:

```
[josevnz@mac-pro-1-1 social-analyzer]$ node -v
v13.6.0
[josevnz@mac-pro-1-1 social-analyzer]$ npm -v
6.13.4
```

**Comment by giga-a** [comment]
Hey, I ran a custom test on my testing system and failed, would you be able to update Node JS to the newer one (v15.5.0)?

[Custom Test Failed - Node JS v13.6.0] -> edec3be9-43b7-4fe5-8e06-796032e1507e

```
> social-analyzer@1.0.0 start /usr/src/app
> node server.js

internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/usr/src/app/node_modules/klona'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/node_modules/sanitize-html/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! social-analyzer@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the social-analyzer@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by giga-a** [comment]
Did it work?

**Comment by kodegeek-test** [comment]
That worked better, I upgraded node to the latest and greatest:


```
[xxx@mac-pro-1-1 ~]$ npm -v
7.3.0
[xxx@mac-pro-1-1 ~]$ node -v
v15.5.0

[xxx@mac-pro-1-1 social-analyzer]$ npm start

> social-analyzer@1.0.0 start
> node server.js

Server started at http://localhost:9005/app.html
```

I tried a basic search (slow user) and I got several errors in the console:

```
Server started at http://localhost:9005/app.html
Command failed: tesseract "/tmp/tmp-7013-cYDHxeZ8agVc" stdout -l eng --oem 1 --psm 3
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.

Total time 73616
```

I tried several well known profiles and I could not get a positive URL, probably because the error above.

I'm closing this issue, I'll wait until version 2.0 gets out.

In any case, thanks for your efforts, looks promising.

**Comment by giga-a** [comment]
Glad to know that it's finally working for you!

The second issue related to tesseract parsing an empty file, I will take a look at it later on..
