### ISSUE TITLE
Errors node.js both way of installation? 

### ISSUE THREAD

**Issue by Andrejki** [qeeqbox/social-analyzer#95]
Hi to everyone! I am new to using this type of web app.
In the meantime I will switch tuousing a pyhton package/script, but I was just wondering is there how to fix this below?
Best regards

Update: Node.js is not working, same error.

```
/social-analyzer$ npm start

> social-analyzer@2.0.32 start /home/andrejki/social-analyzer
> node app.js --gui

/home/andrejki/social-analyzer/app.js:11
import yargs from 'yargs'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! social-analyzer@2.0.32 start: `node app.js --gui`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the social-analyzer@2.0.32 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andrejki/.npm/_logs/2022-12-17T21_19_48_370Z-debug.log
```

**Comment by Andrejki** [comment]
It has many false positives using just python package.

**Comment by giga-a** [comment]
@Andrejki I will take a look

**Comment by Andrejki** [comment]
Everything is ok. 
Npm and node needs to be updated for Webapp. These are my solutions helped by one person.
https://www.geeksforgeeks.org/how-to-solve-npm-error-npm-err-code-elifecycle/
https://phoenixnap.com/kb/update-node-js-version

Thanks! Best regards.
